name: BuildSwiftDylib
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: 原生Xcode编译
        run: xcodebuild build -project *.xcodeproj -configuration Release -arch arm64 -sdk iphoneos clean build

      - name: 提取dylib文件
        run: |
          mkdir out
          find . -name "*.dylib" -type f -exec cp {} out/ \;
          find ~/Library/Developer/Xcode/DerivedData -name "*.dylib" -type f -exec cp {} out/ \;

      - uses: actions/upload-artifact@v4
        with:
          name: MyDylib
          path: out/
