name: SwiftTweakBuild
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      
      - name: 最简编译
        run: |
          brew install theos
          make clean
          make package
      
      - name: 提取文件
        uses: actions/upload-artifact@v4
        with:
          name: dylib-deb
          path: |
            packages/*.deb
            .theos/obj/*.dylib
